# Generated by Django 2.1.7 on 2019-03-24 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, upload_to='static/media/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clinic.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('text', models.TextField()),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='static/media/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.ImageField(blank=True, upload_to='static/media/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNumber', models.SmallIntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clinic.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='results',
            name='visit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Clinic.Visits'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Clinic.Rooms'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Patient'),
        ),
    ]
