# Generated by Django 2.1.7 on 2019-02-22 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('surname', models.TextField(max_length=50)),
                ('specialization', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('surname', models.TextField(max_length=50)),
                ('dateOfBirth', models.DateField(default=None)),
                ('doctors', models.ManyToManyField(to='Clinic.Doctors')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNumber', models.SmallIntegerField(default=None)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Doctors')),
            ],
        ),
    ]
