# Generated by Django 2.1.7 on 2019-02-27 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('text', models.TextField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Clinic.Patient')),
            ],
        ),
    ]
