# Generated by Django 2.1.7 on 2019-02-22 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.ImageField(upload_to='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Patients')),
            ],
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='specialization',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Clinic.Doctors'),
        ),
        migrations.AddField(
            model_name='categories',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Clinic.Doctors'),
        ),
    ]
