# Generated by Django 2.1.7 on 2019-03-10 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0002_auto_20190310_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clinic.Patient'),
        ),
    ]
