# Generated by Django 2.1.7 on 2019-02-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0003_remove_doctors_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='surname',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
