# Generated by Django 2.1.7 on 2019-02-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0004_auto_20190222_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='email',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
