# Generated by Django 2.1.7 on 2019-02-22 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0005_patients_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Patients')),
            ],
        ),
    ]
