# Generated by Django 2.1.7 on 2019-03-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0005_results_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='paper',
            field=models.ImageField(default='results.jpg', upload_to=''),
        ),
    ]
